### ISSUE TITLE
quoted/qoutel allies (darkqoute and lightquote)

### ISSUE THREAD

**Issue by Aid0nModder** [Aid0nModder/AidanBot#15]

**Comment by devxan** [comment]
Indepth aliases (alternate names) info:
**`$quote`** - `$darkquote` `$quoted` `$darkmodequote` `$quotedark`
**`$lightquote`** `$quotel` `$lightmodequote` `$quotelight`

**Comment by Aid0nModder** [comment]
added for V1.3
