### ISSUE TITLE
[ On Hold ] Langauges

### ISSUE THREAD

**Issue by Aid0nModder** [Aid0nModder/AidanBot#50]
Slash commands have some good language support so i'm considering adding langages is the very distant future.

If you speak a language like spanish, french or any other common language, drop a message on this issue if you'd be up to doing some translations.

**Comment by Aid0nModder** [comment]
Things that would be localized
- Command names and descriptions
- All command bodies and fields

Things that can't be localised
- Bot About Me
- ReplyBot

**Comment by NH1507** [comment]
i can speak a little bit of canadian french so maybe i can help with that

**Comment by Aid0nModder** [comment]
I think i should wait until there is at least some people who would use it, it's a lot of work

**Comment by Aid0nModder** [comment]
I closed it for literally no reason

**Comment by Aid0nModder** [comment]
As of now I don't see this being plausible, may reopen in the future
