### ISSUE TITLE
[ Planned V2.1 ] Allow Fight to leave a log of the attacks used

### ISSUE THREAD

**Issue by BockyBlock** [Aid0nModder/AidanBot#75]

**Comment by BockyBlock** [comment]
OOPS didn't mean to submit that yet
enter key moment

**Comment by Aid0nModder** [comment]
I've considered doing something like that, it was even a feature at one point, kinda.

Would be possible and i do plan to revisit fight for V2.1, considering.

**Comment by Aid0nModder** [comment]
Update: just had a thought, what if I used a thread to store the logs :thonk:

That could work, and it wouldn't cause any clutter then, so i can make them more detailed.

**Comment by Aid0nModder** [comment]
Added
